BEGIN;

CREATE TABLE stat (
stat_id BIGSERIAL UNIQUE NOT NULL,
name VARCHAR(64) PRIMARY KEY,
description VARCHAR NOT NULL DEFAULT ''
);

CREATE TABLE power (
power_id BIGSERIAL UNIQUE NOT NULL,
name VARCHAR(64) PRIMARY KEY,
description VARCHAR NOT NULL DEFAULT ''
);

CREATE TABLE influence (
influence_id BIGSERIAL UNIQUE NOT NULL,
name VARCHAR(64) PRIMARY KEY,
description VARCHAR NOT NULL DEFAULT ''
);

CREATE TABLE clan (
clan_id BIGSERIAL PRIMARY KEY NOT NULL,
name VARCHAR(64) UNIQUE NOT NULL,
unique_power VARCHAR(64) NOT NULL,
power_one VARCHAR(64) NOT NULL,
power_two VARCHAR(64) NOT NULL,
description VARCHAR NOT NULL DEFAULT '',

FOREIGN KEY (unique_power) REFERENCES power,
FOREIGN KEY (power_one) REFERENCES power,
FOREIGN KEY (power_two) REFERENCES power
);

COMMIT;
